/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 */

package com.huawei.demo.health.auth

import android.app.Activity
import java.util.function.Consumer

import android.content.Context
import android.content.Intent
import android.os.Bundle
import android.util.Log
import android.webkit.WebResourceRequest
import android.webkit.WebView
import android.webkit.WebViewClient
import androidx.appcompat.app.AppCompatActivity

import com.google.gson.JsonParser
import com.huawei.demo.health.OkHttpUtilCallback
import com.huawei.demo.health.R

import okhttp3.FormBody
import okhttp3.OkHttpClient
import okhttp3.Request

/**
 * Huawei ID signing In and authorization By restful API
 *
 * @since 2020-09-23
 */
class HealthKitCloudLogin : AppCompatActivity() {

    // webview to html
    private var mWebView: WebView? = null

    // okhttp3 OkHttpClient to send request
    private val mClient = OkHttpClient()


    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_health_cloud_login)

        // init WebView config
        initWebView()
    }

    private fun initWebView() {
        mWebView = this.findViewById(R.id.webView)
        mWebView!!.settings.javaScriptEnabled = true
        mWebView!!.settings.useWideViewPort = true
        mWebView!!.settings.loadWithOverviewMode = true
        mWebView!!.settings.builtInZoomControls = true
        mWebView!!.settings.displayZoomControls = false
        mWebView!!.settings.setSupportZoom(true)

        // Customize the WebViewClient and Override the shouldOverrideUrlLoading method to query AccessToken after
        // Huawei ID sign In success. It is used only in the sample code, in the actual scenario, this query can be
        // processed on the callback page.
        mWebView!!.webViewClient = object : WebViewClient() {
            override fun shouldOverrideUrlLoading(view: WebView, request: WebResourceRequest): Boolean {
                Log.i(TAG, request.toString())
                val url = request.url.toString()
                // Intercept redirect_uri to query access token.
                if (url.startsWith("http://www.example.com")) {
                    val code = request.url.getQueryParameter("code")
                    queryAccessToken(code)
                    return true
                }

                // others only call super method
                return super.shouldOverrideUrlLoading(view, request)
            }

        }
        mWebView!!.loadUrl(CLOUD_AUTH)
    }

    /**
     * Use the authorization code to generate the access token.
     *
     * @param code Authorization Code
     */
    private fun queryAccessToken(code: String?) {
        // 1. Build access token request
        val request = buildAtRequest(code)

        // 2. Sending an asynchronous HTTP Request to generate the access token, and build user-defined Callback for
        // response. This Callback init with an anonymous Consumer to get access token and start
        // HealthKitAuthCloudActivity for check HUAWEI Health authorization result.
        mClient.newCall(request).enqueue(
            OkHttpUtilCallback(Consumer<String> { response ->
                // Parse response to get access token
                val jsonObject = JsonParser().parse(response).asJsonObject
                val accessToken = jsonObject.get("access_token").asString

                // Set accessToken result to HealthKitAuthCloudActivity
                val intent = Intent()
                intent.putExtra("accessToken", accessToken)
                setResult(Activity.RESULT_OK, intent)
                finish()
            })
        )
    }

    /**
     * Build restful request to generate the access token
     *
     * @param code Authorization Code from sign in HUAWEI ID
     * @return Request to generate the access token
     */
    private fun buildAtRequest(code: String?): Request {
        val requestBody = FormBody.Builder().add("code", code!!)
            .add("grant_type", "authorization_code")
            .add("client_id", CLIENT_ID)
            .add("client_secret", CLIENT_SECRET)
            .add("redirect_uri", REDIRECT_URI)
            .build()

        return Request.Builder().url(CLOUD_TOKEN)
            .header("Content-Type", "application/x-www-form-urlencoded")
            .post(requestBody)
            .build()
    }

    companion object {
        private val TAG = "HealthKitCloudLogin"

        // the app ID information generated by the Developer Alliance when creating the Server application
        private val CLIENT_ID = "{appid}"

        // the secret information generated by the Developer Alliance when creating the Server application
        private val CLIENT_SECRET = "{secret}"

        // The value of redirect_uri must be the same as the Redirect_URI registered by developer, this only for example.
        private val REDIRECT_URI = "http://www.example.com"

        // URL to query access token
        private val CLOUD_TOKEN = "https://oauth-login.cloud.huawei.com/oauth2/v3/token"

        /**
         * URL of Huawei ID signing In and authorization Health Kit scopes
         * The value of redirect_uri must be the same as the Redirect_URI registered by developer, this only for example.
         */
        private val CLOUD_AUTH =
            "https://oauth-login.cloud.huawei.com/oauth2/v3/authorize?response_type=code&client_id=101489619&redirect_uri=http%3a%2f%2fwww.example.com&scope=https%3A%2F%2Fwww.huawei.com%2Fhealthkit%2Fheightweight.both+https%3A%2F%2Fwww.huawei.com%2Fhealthkit%2Fgoals.both+https%3A%2F%2Fwww.huawei.com%2Fhealthkit%2Findex.both+https%3A%2F%2Fwww.huawei.com%2Fhealthkit%2Fstep.both+https%3A%2F%2Fwww.huawei.com%2Fhealthkit%2Fdistance.both+https%3A%2F%2Fwww.huawei.com%2Fhealthkit%2Fspeed.both+https%3A%2F%2Fwww.huawei.com%2Fhealthkit%2Fcalories.both+https%3A%2F%2Fwww.huawei.com%2Fhealthkit%2Fpulmonary.both+https%3A%2F%2Fwww.huawei.com%2Fhealthkit%2Fstrength.both+https%3A%2F%2Fwww.huawei.com%2Fhealthkit%2Factivity.both+https%3A%2F%2Fwww.huawei.com%2Fhealthkit%2Flocation.both+https%3A%2F%2Fwww.huawei.com%2Fhealthkit%2Fbodyfat.both+https%3A%2F%2Fwww.huawei.com%2Fhealthkit%2Fsleep.both+https%3A%2F%2Fwww.huawei.com%2Fhealthkit%2Fheartrate.both+https%3A%2F%2Fwww.huawei.com%2Fhealthkit%2Fstress.both+https%3A%2F%2Fwww.huawei.com%2Fhealthkit%2Frelaxtraining.both+https%3A%2F%2Fwww.huawei.com%2Fhealthkit%2Fnutrition.both+https%3A%2F%2Fwww.huawei.com%2Fhealthkit%2Fhearthealth.both+https%3A%2F%2Fwww.huawei.com%2Fhealthkit%2Fbloodglucose.both+https%3A%2F%2Fwww.huawei.com%2Fhealthkit%2Fbloodpressure.both+https%3A%2F%2Fwww.huawei.com%2Fhealthkit%2Foxygensaturation.both+https%3A%2F%2Fwww.huawei.com%2Fhealthkit%2Fbodytemperature.both+https%3A%2F%2Fwww.huawei.com%2Fhealthkit%2Freproductive.both&access_type=offline&display=touch"
    }
}
